//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLeilao.Core.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaLeilao.Core.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O leiloeiro não pode dar lance no próprio leilão..
        /// </summary>
        public static string ErrorAuctioneerDoNotBidInOwnAuction {
            get {
                return ResourceManager.GetString("ErrorAuctioneerDoNotBidInOwnAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leiloeiro não encontrado.
        /// </summary>
        public static string ErrorAuctioneerNotFound {
            get {
                return ResourceManager.GetString("ErrorAuctioneerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O leilão já terminou..
        /// </summary>
        public static string ErrorAuctionEnded {
            get {
                return ResourceManager.GetString("ErrorAuctionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leilão não encontrado.
        /// </summary>
        public static string ErrorAuctionNotFound {
            get {
                return ResourceManager.GetString("ErrorAuctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O leilão não está aberto para lances..
        /// </summary>
        public static string ErrorAuctionNotOpen {
            get {
                return ResourceManager.GetString("ErrorAuctionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licitante não encontrado..
        /// </summary>
        public static string ErrorBidderNotFound {
            get {
                return ResourceManager.GetString("ErrorBidderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O lance deve ser pelo menos {0} maior que o preço atual..
        /// </summary>
        public static string ErrorBidTooLow {
            get {
                return ResourceManager.GetString("ErrorBidTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao criar o usuário..
        /// </summary>
        public static string ErrorFailToCreateUser {
            get {
                return ResourceManager.GetString("ErrorFailToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha inválidos.
        /// </summary>
        public static string ErrorInvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar leilão.
        /// </summary>
        public static string ErrorOnCreateAuction {
            get {
                return ResourceManager.GetString("ErrorOnCreateAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não autenticado!.
        /// </summary>
        public static string ErrorUserNotAuthenticated {
            get {
                return ResourceManager.GetString("ErrorUserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leilão criado com sucesso.
        /// </summary>
        public static string SuccessAuctionCreated {
            get {
                return ResourceManager.GetString("SuccessAuctionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lance enviado para processamento..
        /// </summary>
        public static string SuccessBidSentToProcessing {
            get {
                return ResourceManager.GetString("SuccessBidSentToProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login realizado com sucesso.
        /// </summary>
        public static string SuccessLoginSuccessful {
            get {
                return ResourceManager.GetString("SuccessLoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário criado com sucesso.
        /// </summary>
        public static string SuccessUserCreated {
            get {
                return ResourceManager.GetString("SuccessUserCreated", resourceCulture);
            }
        }
    }
}
